name: LogInOutdoors
favicon: null
layout_spectrum: 0.02020697365514934
typography_spectrum: 0.39058910706080496
title: 'Log In Outdoors - Backpacking, Lightweight & Ultralight'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4fffb'
    - '#3c572d'
    - '#302620'
    - '#7da2b8'
    - '#8f8f4c'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
